Adding Update-CloudFront

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -380,9 +380,9 @@ jobs:
             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
             if curl -s $API_URL/api/status | grep "ok"
             then
-              exit 1
+              exit 0
             else
-              exit 2
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -399,20 +399,32 @@ jobs:
       - notify-on-fail
       # Here's where you will add some code to rollback on failure  
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  cloudfront-update:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Save Old Workflow ID to kvdb.io
+          command: |
+            export OLD_WORKFLOW_ID=$(aws cloudformation \
+                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                      --no-paginate --output text)
+            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+            curl https://kvdb.io/5RVDmajnRPYj9a7TnvduiF/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --stack-name InitialStack
+      - destroy-environment
+      - revert-migrations
+      - notify-on-fail
+      # Here's where you will add some code to rollback on failure  
 
 # cleanup:
 #     docker:
@@ -453,7 +465,7 @@ workflows:
           context: Slack-Values
       - notify-on-success:
           requires:
-            - smoke-test
+            - cloudfront-update
           context: Slack-Values
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
@@ -476,7 +488,8 @@ workflows:
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
           context: Slack-Values
-      # - cloudfront-update:
-      #     requires: [smoke-test]
+      - cloudfront-update:
+          requires: [smoke-test]
+          context: Slack-Values
       # - cleanup:
       #     requires: [cloudfront-update]
